name: Build and Deploy
on: workflow_dispatch, push
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer Install
        run: composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Generate
        run: |
          php generate.php $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs