name: Build and Deploy
on:
 workflow_dispatch:
 push:
   branches:
     - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer Install
        run: composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Generate
        run: |
          php generate.php $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs