on: [push, pull_request]
name: PHP
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer Install
        run: composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix .  --dry-run --diff